export const GET_PRODUCTS_REQUESTS = 'GET_PRODUCTS_REQUESTS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';

export const GET_PRODUCT_DETAIL_REQUESTS = 'GET_PRODUCTS_REQUESTS';
export const GET_PRODUCT_DETAIL_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCT_DETAIL_FAIL = 'GET_PRODUCTS_FAIL';
export const GET_PRODUCT_DETAIL_RESET = 'GET_PRODUCTS_FAIL';
